samples: samples.tsv
units: units.tsv

params:
  general:
    end1_suffix: "_1"
    end2_suffix: "_2"
    alignment_quality: "10"
  bowtie2:
    cli_params_global: "--very-sensitive --end-to-end"
    index:
      shiny: ""
      gdu: "/home/skurscheid/Data/References/Genomes/Homo_sapiens/GRCh38_ensembl84/canonical/index/hg38_ensembl84"
      gadi: "/scratch/kv78/References/Genomes/Homo_sapiens/GRCh38_ensembl84/canonical/index/hg38_ensembl84"
  fastp: ""
  mcf10a_chip:
    runTable:
      file: 'ChIPRunTable.csv'
      selected_columns: ['BioSample', 'aggregate_column', 'Run']
      aggregate_column: 'aggregate_column'
      chip_input_value: 'none'
